import type { Metadata } from 'next';
import './globals.css';
import '@stackflow/plugin-basic-ui/index.css';
import { Stack } from '@/core/stackflow';
import ClientStack from '@/components/CleintStack';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <ClientStack />
      </body>
    </html>
  );
}
